app:
  update: 60

telegram:
  token: 244516775:AAGZUrt9eQjhGSsFFpbjyNA9su6gQU-Qs
  group: -6596563379

scan:
  hosts:
    - host: 8.8.8.0/24
      ports:
        - 20-23
        - 3389
      exclusion:
        hosts:
          - 8.8.8.1
        ports:
          - 22
    - host: google.com
      ports:
        - 80
        - 443
  
